version: "3.8"
services:
  db:
    image: postgres
    container_name: local_postgres_db
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test_db
    volumes:
      - ./local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    depends_on:
      - db
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 12345
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  local_pgdata:
  pgadmin-data: